# This is a basic workflow to help you get started with Actions

name: Testing Automatin with Cronjob

# Controls when the workflow will run
on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/2 * * * *" # Runs at 03:00 AM (UTC) every Monday, Wednesday, and Friday (Check https://crontab.guru/)



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - name: 🍽️ Checkout the repo
          uses: actions/checkout@main
          with:
            fetch-depth: 1
            
        - name: 🐍 Set up Python 3.8
          uses: actions/setup-python@v2
          with:
            python-version: '3.8'
            
        - name: 📥 Download the Python script needed for automation
          run:  curl https://raw.githubusercontent.com/ccho-0508/CIS3296_proofOCTest/main/testSc.py -o testSc.py

        - name: 🚀 Run Automation
          run: python testSc.py 
          
          
          
#       ${{ secrets.READWISE_TOKEN }} ${{ secrets.ZOTERO_KEY }} ${{ secrets.ZOTERO_ID }}
      
#       - uses: actions/checkout@v2

#       # Runs a single command using the runners shell
#       - name: Run a one-line script
#         run: echo Hello, world!

#       # Runs a set of commands using the runners shell
#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.
